server:
  port: 8769
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /a/**
      serviceId: service-hi
  RibbonRoutingFilter:
    route:
      disable: true
management:
  security:
    enabled: false
neo: 
  hello: qweq123
  